### ISSUE TITLE
Reading

### ISSUE THREAD

**Issue by dicook** [TengMCing/bushfire-paper#1]
- https://cran.r-project.org/web/views/SpatioTemporal.html :  CRAN Task Views on  SpatioTemporal data has a  long, long list of spatiotemporal tools available in R. Currently, sf is the best data handling  package. It replaces sp. 
- https://cran.r-project.org/web/views/TimeSeries.html Similarly the list of all  possible tools foor time series available in R 
- https://www.littlemissdata.com/blog/maps is a nice intro to making maps in R. Its a couple of years out of date, but only the need to have a google api to  pull google maps should be the only change
- https://tidyverts.org tools for temporal data, including  data structures, and forecasting models. You can use these to forecast multiple time series independently
- https://plotly-r.com  Interactive graphics including maps by Carson Sievert. Good  basic tools for animations and plotting principles
- http://socviz.co A good  guide to plotting  data
- https://www.researchgate.net/publication/320223143_Analyzing_spatio-temporal_data_with_R_Everything_you_always_wanted_to_know_-_but_were_afraid_to_ask A nice guide to the modeling, but their graphics are very old-fashioned and should be replaced with approaches from the above links.

**Comment by TengMCing** [comment]
Thank you, Di. I will read these materials carefully.

**Comment by dicook** [comment]
https://link.springer.com/article/10.1007/s11749-010-0209-z

**Comment by dicook** [comment]
https://www.crcpress.com/Spatio-Temporal-Statistics-with-R/Wikle-Zammit-Mangion-Cressie/p/book/9781138711136
